### ISSUE TITLE
Notes on ERC errors

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/OBCBoard_PCB#4]
1. EPS_RX and EPS_TX will now be COMMS_RX and COMMS_TX and should be connected to J19 umbilical
2. ADCS_RW_3V3 can be completely removed
3. VDD_RW can be removed
4. VREF can be removed
5. VDD can be removed
6. USR_ADC_1,2 can be removed
7. MCU_VDDIO, MCU_VDDIN, MCU_VDDIO and the rest of the connections to test points were not supposed to give an error. Something is wrong here
8. EPS_3V3_SU and EPS_12V_SU can also be removed
9. PAY_SWITCH can be removed
10. SU_3V3 and SU_12V can be removed
11. 3V3_PROT on RS-422 OBC sheet is a problem that has to be fixed
12. SU_SWDIO can be removed
13. SU_SWCLK can be removed
14. 3V3_ADCS on RS-422 ADCS sheet is a problem

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/4b19c1e3-8349-4334-a943-f56811b2976d)

**Comment by giatats** [comment]
Fixed many of them, some persist, maybe you can take a look, mainly for the 2 remaining errors.

**Comment by giatats** [comment]
To EPS_5V_ADM ston 104 einai se 2 pin, na ta kanw short?

**Comment by Basilhs-Moustakas** [comment]
For the EPS_5V_ADM yes

For the ERC errors somehow I still get 14 of them. I think that it is just kicad being stupid with the grid though. Can you show me the errors you get?

![image](https://github.com/PeakSat/OBCBoard_PCB/assets/48751090/e4598ceb-ffe4-49d3-b1e1-a5171d6ee78d)
